# Generated by Django 6.0.2 on 2026-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20, verbose_name='Тип приёма пищи')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток порций')),
                ('allergens', models.TextField(blank=True, verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Блюдо меню',
                'verbose_name_plural': 'Меню',
                'unique_together': {('date', 'meal_type', 'name')},
            },
        ),
    ]
