# Generated by Django 6.0.2 on 2026-02-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
