# Generated by Django 6.0.2 on 2026-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], default=1, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='date',
        ),
    ]
