# Generated by Django 6.0.2 on 2026-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_menuitem_unique_together_menuitem_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Приём пищи', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('day_of_week', 'meal_type')},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_items',
            field=models.TextField(default='', verbose_name='Состав меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за приём пищи'),
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
    ]
