# Generated by Django 6.0.2 on 2026-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Пищевые аллергии'),
        ),
    ]
